CREATE TABLE usuarios (
    id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    senha VARCHAR(50) NOT NULL,
    tipo SET('GESTOR','BANDA','COMUM') NOT NULL DEFAULT 'COMUM',
    status SET('ATIVO','INATIVO') NOT NULL DEFAULT 'ATIVO',
    permissao JSON DEFAULT NULL,
    PRIMARY KEY ('id')
)ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci